version: '3'
services:
  movies:
    image: jabinmohammad/pen:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: jabinmohammad/pencil:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: jabinmohammad/marker:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: jabinmohammad/paper:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3

